name: Health Check

on:
  push:
    branches:
      - add-new-feature

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v3
        with:
          url: https://stormy-cliffs-30272.herokuapp.com
        if: ${{ failure() }}
        run: echo "health check failed"